### ISSUE TITLE
Default Install instruction doesn't work

### ISSUE THREAD

**Issue by tovid-suite** [tovid-suite/tovid#118]
_From [gilbertoca](https://code.google.com/u/gilbertoca/) on May 14, 2010 09:27:27_

OS: opensuse 11.2
tovid: 0.32

\<quote>
$ ./configure
$ su -c "make install"
\</quote>
It get installed in /usr/local/bin/tovid.
After install no executable works, giving me this message:
\<quote>
tovid executables assumed to be in '/usr/lib/tovid'
\</quote>

To make it work I have to use the --prefix parameter:
\<quote>
./configure --prefix=/usr
\</quote>

_Original issue: http://code.google.com/p/tovid/issues/detail?id=118_

**Comment by grepper** [comment]
_From [wapcaplet88](https://code.google.com/u/wapcaplet88/) on June 01, 2010 16:37:16_

This should be fixed with the new setup.py installer; it ought to be smarter about
detecting the correct prefix where tovid should be installed (although you may still
need to pass the --prefix parameter). Please try using setup.py in tovid 0.33.

**Owner:** wapcaplet88

**Comment by grepper** [comment]
_From [wapcaplet88](https://code.google.com/u/wapcaplet88/) on June 01, 2010 16:41:07_

**Status:** Questions

**Comment by grepper** [comment]
Closing, as distutils are used now and the problem has not been seen in new reports.
